// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SantaInesAPI.Persistence.Database;

#nullable disable

namespace SantaInesAPI.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20221211140202_Departamentos")]
    partial class Departamentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SantaInesAPI.Persistence.Entity.Departamento", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("SantaInesAPI.Persistence.Entity.Direccion", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cod_postal")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("SantaInesAPI.Persistence.Entity.Usuario", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("Departamentoid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("apellido_completo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("id_direccion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nombre_completo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.HasIndex("Departamentoid");

                    b.HasIndex("id_direccion")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SantaInesAPI.Persistence.Entity.Usuario", b =>
                {
                    b.HasOne("SantaInesAPI.Persistence.Entity.Departamento", null)
                        .WithMany("usuarios")
                        .HasForeignKey("Departamentoid");

                    b.HasOne("SantaInesAPI.Persistence.Entity.Direccion", "Direccion")
                        .WithOne("Usuario")
                        .HasForeignKey("SantaInesAPI.Persistence.Entity.Usuario", "id_direccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("SantaInesAPI.Persistence.Entity.Departamento", b =>
                {
                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("SantaInesAPI.Persistence.Entity.Direccion", b =>
                {
                    b.Navigation("Usuario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
